name: Publish Release
on:
  release:
    types:
      - published
jobs:
  build:
    strategy:
      matrix:
        java: [ 17 ]
        os: [ ubuntu-20.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v3
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - name: Set pre_release
        run: |
          sed -i "s/pre_release=alpha/pre_release=/g" gradle.properties
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: build
        run: |
          ./gradlew preprocessResources
          ./gradlew build
      - name: Find correct JAR
        id: findjar
        run: |
          output="$(find build/libs/ ! -name "*-dev.jar" ! -name "*-sources.jar" -type f -printf "%f\n")"
          echo "::set-output name=jarname::$output"
      - name: Upload assets to GitHub
        uses: AButler/upload-release-assets@v2.0
        if: ${{ runner.os == 'Linux' && matrix.java == '17' }}
        with:
          files: build/libs/${{ steps.findjar.outputs.jarname }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}